### PR TITLE
Upgrade to Rails 7

### PR DESCRIPTION
**Pull request by jbirdjavi**
Other things:
- I removed the ActiveAdmin skin since it hadn't been maintained since 2015 and was falling behind. The default skin will be easier to maintain going forward.
- Using importmaps required an ActiveAdmin upgrade and some tweaks
- Had to monkeypatch Devise to allow logout redirects

### CODE REVIEW

**Review by knutsenm — COMMENTED** [review]
Is anything else affected by the move of the campaign-form.js file, like for example app/javascript/packs/campaign.js:4 ?

**Comment by jbirdjavi** [comment]
> Is anything else affected by the move of the campaign-form.js file, like for example app/javascript/packs/campaign.js:4 ?

Well the file you referenced no longer exists. :) But yeah, I think all references to that should be good now.

**Comment by knutsenm** [comment]
> Well the file you referenced no longer exists. :) But yeah, I think all references to that should be good now.

Oops, sorry! I checked master first but forgot to recheck your branch.

**Review by knutsenm — APPROVED** [review]
> Other things:

Wow. Thanks for figuring out all that!

**Comment by jbirdjavi** [comment]
@knutsenm Do you know if there's anyone that I should notify about the skin being changed before I deploy?

**Comment by wrandall22** [comment]
If the look/feel is changing, cru.org will be impacted I presume.

**Comment by wrandall22** [comment]
@j2trumpet are you able to test this on stage.cru.org?

**Comment by knutsenm** [comment]
> anyone that I should notify about the skin being changed before I deploy?

No.

> @j2trumpet are you able to test this on stage.cru.org?

Yes, please! We could use a staging test before production deploy.

**Comment by j2trumpet** [comment]
@wrandall22 @knutsenm @jbirdjavi  The latest Adobe Campaign form code I've worked with was for the cru.org newsletter. I just created a test page on stage, put in just enough code to recreate the newsletter form with styling, and it looks as expected, so I'm thinking these changes are safe to push to prod.

**Pull request merged**
